resolver: lts-13.22

packages:
- .
# - prelude
# - lorentz-contracts
# - indigo

extra-deps:
# - constraints-0.11.2@sha256:d028005d93f891b48b61ff0c82c6f868859eb728010dea3e355b0c55d0f57cf9
# - type-equality-1@sha256:aeb9c44abf5d2edf52caff114a7da565d8328fa84bbe194828e4355ea85bf5b3
- aeson-options-0.1.0
- base58-bytestring-0.1.0
- constraints-0.11
- hex-text-0.1.0.0
- pretty-terminal-0.1.0.0
- show-type-0.1.1
- first-class-families-0.6.0.0@sha256:9d2a2a0092dfb8fd0e688b0b6bf71242fbc393c028b0b669d25ed387667490c2
- git:
    https://gitlab.com/morley-framework/morley.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    40dd07b9ffd9a5b1a6898708dd829a881f6ba02a # master
  subdirs:
    - .
    - prelude
    - morley-upgradeable
    - morley-ledgers
    - morley-ledgers-test
    - indigo

nix:
  shell-file: shell.nix
